version: '3.9'
services:
  dbmysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./database/db:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: exito
      MYSQL_DATABASE: dbpractice
    ports:
      - "3306:3306"
    networks:
      - net

  servicio1:
    build: ./servicio1
    ports:
      - "3001:3001"
    networks:
      - net
    depends_on:
      - dbmysql

  servicio2:
    build: ./servicio2
    ports:
      - "3002:3002"
    networks:
      - net
    depends_on:
      - dbmysql

  servicio3:
    build: ./servicio3
    ports:
      - "3003:3003"
    networks:
      - net
    depends_on:
      - dbmysql

networks:
  net: {}
